# Generated by Django 5.2.4 on 2025-07-11 23:54

import cursos.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreNivel', models.CharField(max_length=20, validators=[cursos.validators.validar_alfabetico, cursos.validators.validar_longitud_minima])),
                ('posicion_ordinal', models.PositiveIntegerField(default=1, validators=[cursos.validators.validar_entero_positivo])),
                ('estado', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreParalelo', models.CharField(max_length=1, validators=[cursos.validators.validar_alfabetico, cursos.validators.validar_un_solo_caracter])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreGrado', models.CharField(max_length=100, validators=[cursos.validators.validar_alfabetico])),
                ('posicion_ordinal', models.PositiveIntegerField(default=1, validators=[cursos.validators.validar_entero_positivo])),
                ('estado', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCurso', models.CharField(max_length=100, validators=[cursos.validators.validar_longitud_minima])),
                ('estado', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.grado')),
                ('paralelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.paralelo')),
            ],
        ),
    ]
