# Generated by Django 5.2.4 on 2025-07-11 23:55

import calificaciones.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_gestion', models.CharField(max_length=10, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_asignatura', models.CharField(max_length=45)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_periodo', models.CharField(max_length=45)),
                ('posicion_ordinal', models.PositiveSmallIntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='calificaciones.gestion')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_general', models.PositiveSmallIntegerField(blank=True, null=True, validators=[calificaciones.validators.validar_calificacion])),
                ('calificacion_ser', models.PositiveSmallIntegerField(blank=True, null=True, validators=[calificaciones.validators.validar_calificacion])),
                ('calificacion_saber', models.PositiveSmallIntegerField(blank=True, null=True, validators=[calificaciones.validators.validar_calificacion])),
                ('calificacion_hacer', models.PositiveSmallIntegerField(blank=True, null=True, validators=[calificaciones.validators.validar_calificacion])),
                ('calificacion_decidir', models.PositiveSmallIntegerField(blank=True, null=True, validators=[calificaciones.validators.validar_calificacion])),
                ('calificacion_autoevaluacion', models.PositiveSmallIntegerField(blank=True, null=True, validators=[calificaciones.validators.validar_calificacion])),
                ('estado', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.asignatura')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.estudiante')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.periodo')),
            ],
        ),
    ]
