# Generated by Django 5.2.4 on 2025-07-12 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificacion',
            old_name='calificacion_decidir',
            new_name='calificacion_actitudes',
        ),
        migrations.RenameField(
            model_name='calificacion',
            old_name='calificacion_hacer',
            new_name='calificacion_conocimiento',
        ),
        migrations.RenameField(
            model_name='calificacion',
            old_name='calificacion_saber',
            new_name='calificacion_pensamiento_critico',
        ),
        migrations.RenameField(
            model_name='calificacion',
            old_name='calificacion_ser',
            new_name='calificacion_practica',
        ),
    ]
